name: CMake

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        BUILD_SHARED_LIBS: ["ON", "OFF"]

    steps:
    - uses: actions/checkout@v1

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DBUILD_SHARED_LIBS=${{matrix.BUILD_SHARED_LIBS}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .

    # TODO: add tests to the pipeline
    # - name: Test
    #   working-directory: ${{runner.workspace}}/build
    #   shell: bash
    #   run: ctest .