name: CMake

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        BUILD_SHARED_LIBS: ["ON", "OFF"]
        ENABLE_DTLS: ["ON", "OFF"]
        ENABLE_TCP: ["ON", "OFF"]
        # TODO add cryto backend to matrix -> huge pain on windows without conan

    steps:
    - uses: actions/checkout@v1

    - name: setup (win)
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install openssl.light

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DENABLE_EXAMPLES=ON -DBUILD_SHARED_LIBS=${{matrix.BUILD_SHARED_LIBS}} -DENABLE_DTLS=${{matrix.ENABLE_DTLS}} -DENABLE_TCP=${{matrix.ENABLE_TCP}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .

    # TODO: add tests to the pipeline
    # - name: Test
    #   working-directory: ${{runner.workspace}}/build
    #   shell: bash
    #   run: ctest .