name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        BUILD_SHARED_LIBS: ["ON", "OFF"]
        ENABLE_DTLS: ["ON", "OFF"]
        ENABLE_TCP: ["ON", "OFF"]
        ENABLE_EXAMPLES: ["ON", "OFF"]
        ENABLE_TESTS: ["ON", "OFF"]
        DTLS_BACKEND: ["openssl", "gnutls", "mbedtls", "tinydtls"]
        include:
          - os: windows-latest
            DTLS_BACKEND: "openssl"
            ENABLE_EXAMPLES: "OFF"
            ENABLE_TESTS: "OFF"
          # - os: macos-latest
          #   DTLS_BACKEND: "openssl"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install libcunit1-dev libmbedtls-dev libgnutls28-dev

      - name: setup (windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install openssl

      - name: setup (mac)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew upgrade
          brew install cmake openssl

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE \
          -DENABLE_EXAMPLES=${{matrix.ENABLE_EXAMPLES}} \
          -DENABLE_TESTS=${{matrix.ENABLE_TESTS}} \
          -DBUILD_SHARED_LIBS=${{matrix.BUILD_SHARED_LIBS}} \
          -DENABLE_DTLS=${{matrix.ENABLE_DTLS}} \
          -DENABLE_TCP=${{matrix.ENABLE_TCP}} \
          -DDTLS_BACKEND=${{matrix.DTLS_BACKEND}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build .

    # TODO: add tests to the pipeline
    # - name: Test
    #   working-directory: ${{runner.workspace}}/build
    #   shell: bash
    #   run: ctest .
